repos:
  # Ruff (lint + autofix)
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix]
        # same 100-char line length picked in pyproject.toml
        additional_dependencies: ["ruff==0.4.4"]

  # Black (format)
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        args: ["--line-length", "100"]

  # Mypy (type-check; read-only)
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
